### ISSUE TITLE
incorrect region

### ISSUE THREAD

**Issue by youryazhuo** [qiniudemo/qiniu-api-server#2]
error:please use up-z1.qiniu.com
我已经修改了/qiniu/conf.php里面的$QINIU_UP_HOST = 'http://up-z1.qiniu.com';可以还是出现同样的错误，求助。

**Comment by jemygraw** [comment]
这个服务只是用来生成token给客户端上传使用的。如果你需要用php sdk，可以下载 php sdk的最新版本。
